name: install_script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  vm:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install latest version
      run: |
        ./install_linux.sh
        tofulint -v
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install specific version
      env:
        TOFULINT_VERSION: v0.15.0
      run: |
        ./install_linux.sh
        tofulint -v
    - name: Install to custom path
      run: |
        mkdir "$TOFULINT_INSTALL_PATH"
        ./install_linux.sh
        "$TOFULINT_INSTALL_PATH/tofulint" -v
      env:
        TOFULINT_INSTALL_PATH: ${{ github.workspace }}/install-path
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
    - name: Non-existent version
      id: fail
      continue-on-error: true
      # Install instructions pipe the script from curl to bash
      # Passing scripts via stdin can have differing behavior from passing as a file arg
      run: |
        bash < install_linux.sh
        tofulint -v
      env:
        TOFULINT_VERSION: vBROKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check failure
      if: steps.fail.outcome != 'failure'
      run: |
        echo "::error::Expected previous step to fail, outcome was ${{ steps.fail.outcome }}"
        exit 1

  container:
    runs-on: ubuntu-latest
    container:
      image: opentofu
      options: --user 0
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        apk add bash curl curl-dev unzip
    - name: Install latest version
      run: |
        ./install_linux.sh
        tofulint -v
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install specific version
      env:
        TOFULINT_VERSION: v0.15.0
      run: |
        ./install_linux.sh
        tofulint -v
